### ISSUE TITLE
Coma (,) charater is not executed on the server

### ISSUE THREAD

**Issue by asosso** [appleboy/drone-ssh#77] opened 2017-05-08 17:29 UTC
**drone.yml**

```
test-coma:
    image: appleboy/drone-ssh
    host:
     - 192.168.1.2
    username: ubuntu
    port: 22
    script:
      - echo ","
```

**Output**

```
2017/05/08 17:27:56 192.168.1.2: commands:  echo "
"
2017/05/08 17:27:57 192.168.1.2: outputs: 
2017/05/08 17:27:57 Successfully executed commands to all host.
exit code 0
```

**Comment by appleboy** [comment] 2017-05-09 08:56
duplicate of https://github.com/appleboy/drone-ssh/issues/60

**Closed by appleboy** 2017-05-09 08:56 UTC
